// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm8L0JohaJYa0VQLFbzH6GN-nf3lI7gTU',
    appId: '1:939548000024:web:093d334f9cf74d4b64286d',
    messagingSenderId: '939548000024',
    projectId: 'veterinarian-95d68',
    authDomain: 'veterinarian-95d68.firebaseapp.com',
    storageBucket: 'veterinarian-95d68.appspot.com',
    measurementId: 'G-H2YPX5FTQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfA0iVHaO_QHYTDerSKYD9lz1AdlBjZAw',
    appId: '1:939548000024:android:2d6a27bd41b9f7b864286d',
    messagingSenderId: '939548000024',
    projectId: 'veterinarian-95d68',
    storageBucket: 'veterinarian-95d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD955RXHicV0Ur-mIzyV_3VWtKInp_CfII',
    appId: '1:939548000024:ios:8e2611e9d310a81964286d',
    messagingSenderId: '939548000024',
    projectId: 'veterinarian-95d68',
    storageBucket: 'veterinarian-95d68.appspot.com',
    iosBundleId: 'com.abdelrahman1917.pawInOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD955RXHicV0Ur-mIzyV_3VWtKInp_CfII',
    appId: '1:939548000024:ios:8e2611e9d310a81964286d',
    messagingSenderId: '939548000024',
    projectId: 'veterinarian-95d68',
    storageBucket: 'veterinarian-95d68.appspot.com',
    iosBundleId: 'com.abdelrahman1917.pawInOut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm8L0JohaJYa0VQLFbzH6GN-nf3lI7gTU',
    appId: '1:939548000024:web:51c4583189f7a56264286d',
    messagingSenderId: '939548000024',
    projectId: 'veterinarian-95d68',
    authDomain: 'veterinarian-95d68.firebaseapp.com',
    storageBucket: 'veterinarian-95d68.appspot.com',
    measurementId: 'G-7S7H7VFE47',
  );
}
